### ISSUE TITLE
Requiring quantities doesn't work right inside of functions

### ISSUE THREAD

**Issue by MarkGillespie** [nmwsharp/geometry-central#15]
Sometimes when I require quantities inside of functions geometry-central doesn't fill the associated buffer. For example, if I try to run the following code, I segfault at the `std::cout` line.

``` c++
#include "geometrycentral/surface/halfedge_mesh.h"
#include "geometrycentral/surface/meshio.h"
#include "geometrycentral/surface/vertex_position_geometry.h"

#include "args/args.hxx"
#include "imgui.h"

using namespace geometrycentral;
using namespace geometrycentral::surface;

// == Geometry-central data
std::unique_ptr<HalfedgeMesh> mesh;
std::unique_ptr<VertexPositionGeometry> geometry;

void badFn(VertexPositionGeometry geo) {
  geo.requireVertexAngleSums();
  std::cout << geo.vertexAngleSums[0] << std::endl;
}

int main(int argc, char **argv) {

  // Configure the argument parser
  args::ArgumentParser parser("geometry-central & Polyscope example project");
  args::Positional<std::string> inputFilename(parser, "mesh", "A mesh file.");

  // Parse args
  try {
    parser.ParseCLI(argc, argv);
  } catch (args::Help) {
    std::cout << parser;
    return 0;
  } catch (args::ParseError e) {
    std::cerr << e.what() << std::endl;
    std::cerr << parser;
    return 1;
  }

  // Make sure a mesh name was given
  if (!inputFilename) {
    std::cerr << "Please specify a mesh file as argument" << std::endl;
    return EXIT_FAILURE;
  }

  // Load mesh
  std::tie(mesh, geometry) = loadMesh(args::get(inputFilename));

  // Uncomment to fix
  // geometry->requireVertexAngleSums();
  badFn(*geometry);

  return EXIT_SUCCESS;
}

```
Error message:
```
Assertion failed: (i < size() && "Attempted to access MeshData with out of bounds index"), function operator[], file /Users/mark/Documents/Code/bad-gc-mesh/deps/geometry-central/src/../include/geometrycentral/surface/halfedge_containers.ipp, line 209.
```

If I call `requireVertexAngleSums` before calling `badFn`, then everything works fine.

You can find this example in a repo here: https://github.com/MarkGillespie/bad-gc-mesh.

**Comment by nmwsharp** [comment]
Thanks for the issue!

If I'm reading this right, `void badFn(VertexPositionGeometry geo)` takes the geometry argument by value. So what's actually happening when you call the function is that you create a copy of the geometry, and then `require()` the quantity on that copy. When the function returns, the copy is discarded, and nothing has been computed on the original geometry object. (unless I'm missing something)

Perhaps the real bug here is that the geometry object is getting silently copy-constructed, when that's usually not the desired behavior. I thought I had removed all the copy constructors, but  apparently not... they are useful sometimes.

**Comment by nmwsharp** [comment]
For instance, changing the function to take the geometry object by reference like
```
void badFn(VertexPositionGeometry& geo)
```
fixes the issue in the example repo.

**Comment by MarkGillespie** [comment]
Great!

I guess now we're in the territory of weird c++ questions, but I don't understand why this silent copy causes problems in the code. I call `vertexAngleSums()` on `geo`, so even though it's a copy and not the original `geometry`, shouldn't it still have the `vertexAngleSums` filled out? I only use these angles inside of the function.

**Comment by nmwsharp** [comment]
Oh yeah, good point. Everything should still work fine if you actually _do_ want to construct a copy. Perhaps an implicit copy constructor is getting erroneously used, and it's not copying all all the data properly? I can take a look.

**Comment by nmwsharp** [comment]
Ah yeah, this is a bug. Looks like the implicit move constructors (and destructor, actually) on the geometry classes are a mess. 

I'll push a fix before long, though I want to take a little time to think about how this should work to get it right.

**Comment by nmwsharp** [comment]
Ok, the fix is in the `bugfix` branch. Pull request here: https://github.com/nmwsharp/geometry-central/pull/16. 

Basically, the code in your example will no longer compile, as the implicit copy constructor is deleted. To copy geometry objects, there's an explicit `VertexPositionGeometry::copy()` method. The new copy does not initially have any quantities required. 

I'll wait until Monday to merge this to master; I'll be traveling tomorrow and don't want to push a possibly-breaking change before going AFK :)
