### ISSUE TITLE
About Curvature-Aligned Vertex Direction Field

### ISSUE THREAD

**Issue by mikeshuangyan** [nmwsharp/geometry-central#159]
Hi,

I'm trying to generate a Curvature-Aligned Vertex Direction Field. I have replaced the "computeSmoothestVertexDirectionField" function with "computeCurvatureAlignedVertexDirectionField" in the direction_fields tutorial, and this is what I get:
![image](https://github.com/nmwsharp/geometry-central/assets/2291818/a5af6a9a-04b2-403b-93c4-8cc7d562f1a6)

Anyone know how to call "computeCurvatureAlignedVertexDirectionField" function?

Best,
Lu

**Comment by nmwsharp** [comment]
Hi! 

[The culprit here is probably the representation used for symmetric vector fields](https://geometry-central.net/surface/algorithms/direction_fields/#interpreting-symmetric-direction-fields). For symmetric fields, geometry-central returns `v^n` for each vector, where `v` is your tangent vector as a complex number, and `n` is the symmetry order, probably `n=2` or `n=4` in your case, since curvature alignment only makes sense for symmetric direction fields. The complex power is used so that the 2 (resp. 4) different directions are represented by the same vector. This paper is the relevant reference: https://www.cs.cmu.edu/~kmcrane/Projects/GloballyOptimalDirectionFields/paper.pdf

Anyway, if you naively visualize these complex-vectors-raised-to-the-nth-power, they will look like nonsense. You generally want to take the `n`'th root, and then the 2 (resp. 4) solutions to the `n`'th root give the actual vectors of the symmetric field.

It looks like you're using Polyscope. Polyscope contains some built-in features for visualizing such fields, so you don't have to mess with taking the root yourselve. You can set the `nSym` argument here https://polyscope.run/structures/surface_mesh/vector_quantities/#adding-intrinsic-tangent-vectors to automatically take the complex root for you and visualize each root as a repeated vector.

(Confusingly, I am in the midst of changing Polyscope's API related to these symmetric vector fields. If you pull the very latest commit from Polyscope these functions are renamed to `addTangentVector`, and the `nSym` works differently... I'd recommend just sticking with the slightly older `addVertexIntrinsicVectorQuantity` for now.)

**Comment by mikeshuangyan** [comment]
Hi,

Thank you for your quick response.

I found the problem in my code, when I call addVertexIntrinsicVectorQuantity, I need to set nSym value, default value is 1.
Thank you for your help.

Best,
Lu
