### ISSUE TITLE
trivial navigation question

### ISSUE THREAD

**Issue by afabri** [nmwsharp/geometry-central#191]
I am wondering what I understand wrong that the assertion fails.  `mesh` consists of two triangles sharing an edge.
```
for( auto v : mesh->vertices()){
    assert(v == v.halfedge().twin().tipVertex());
  }
```

**Comment by nzfeng** [comment]
I did some experiments and found that 
(1) Only boundary vertices trigger assertion failure, but not all boundary vertices.
(2) Assertion failure only happens when a mesh is created as a `SurfaceMesh`, but not as a `ManifoldSurfaceMesh`. 
(3) When the assertion fails, `v.halfedge()` works as expected, but `v.halfedge().twin()` returns the same halfedge as `v.halfedge()`.

The cause of this behavior seems to be [line 193 in `surface_mesh.cpp`](https://github.com/nmwsharp/geometry-central/blob/master/src/surface/surface_mesh.cpp#L193):

```
if (heSiblingArr[lastHe] == INVALID_IND) {
    // Any edges which never got any sibling entries at all are boundary halfedges
    heSiblingArr[lastHe] = lastHe;
    continue;
}
```
I changed this code to the below but didn't fix the behavior.
```
if (heSiblingArr[lastHe] == INVALID_IND) {
    // Any edges which never got any sibling entries at all are boundary halfedges
    heSiblingArr[lastHe] = iHe;
    heSiblingArr[iHe] = lastHe;
    heEdgeArr[iHe] = heEdgeArr[lastHe];
    heOrientArr[iHe] = !heOrientArr[lastHe];
    iHe++;
    continue;
}
```
@nmwsharp what else do I need to change (and if I make these changes, will anything else break?)

**Comment by afabri** [comment]
Let me ask another question concerning a `ManifoldSurfaceMesh` without borders.    I would expect that
`assert(h.edge().halfedge() == h)`  holds for all halfedges, but it does not.  Would that be easy to guarantee?

**Comment by nzfeng** [comment]
Sadly I don't think it will be easy to guarantee, and may lead to counterintuitive results -- 

The convention we've used is that `edge.halfedge()` returns an arbitrary but fixed halfedge of `edge`. Since there are at least two distinct halfedges per edge, it makes sense the assertion wouldn't hold for at least one halfedge of each edge. Whether a given halfedge aligns with its edge's canonical orientation can be in fact tested using the value of `h.edge().halfedge()` or `he.orientation()`.

To make your assertion hold always, an `Edge` object's `halfedge()` function would always need to know which element(s) came before it in the chain of commands, if any, which would be tricky to implement. I think making this change now may also be breaking in many cases, or counterintuitive to people who are used to this convention.

**Comment by nmwsharp** [comment]
Hi!

For the original question about  `assert(v == v.halfedge().twin().tipVertex());` and boundary halfedges' twins:

I intentionally implemented it this way, although it may have been a mistake, and I'm open to changing it!

As you know, on a manifold & oriented halfedge mesh, each halfedge always has exactly one twin which points in the opposite direction. This is true even with boundary, by introducing fake "boundary loop" faces and exterior halfedges. So in this case, we guarantee that the twin operator behaves like an involution, and that `he.twin()` points in the opposite direction. 

However, in the general not-necessarily-manifold and not-necessarily-oriented case, this all goes out the window. Since the mesh might not be oriented, we can't guarantee that a halfedge and its twin point in opposite directions, even at a manifold interior edge. At nonmanifold edges there could be 3 or more halfedges on an edge, so "twin()" is a misnomer. At the boundary, boundary "loops" do not necessarily exist, we may not be able to group exterior halfedges into face loops.

For all these reasons, the handling of the general case is a bit different. In a general `SurfaceMesh`:
- (1) we do not guarantee that `halfedge()` and `halfedge.twin()` point in opposite directions
- (2) `twin()` is not necessarily an involution, calling it repeatedly orbits around the halfedges at an edge (it is aliased to `sibling()` for this reason, which is a better name)
- (3) Along the boundary, there are no exterior halfedges. We don't create them because there is no clear way to group them into boundary loops anyway. And since `twin()` is now an orbit, it is fine for this to be an orbit of size one. A boundary halfedge's has `he.twin() == he`. We don't need the concept of exterior halfedges, and we dodge the fact that boundary loops would not be well-defined.

I do see how this can be confusing, because all of this changes even if you load a mesh which does happen to be manifold & oriented, but you load it as a general `SurfaceMesh`, you immediately lose a bunch of properties & behavior changes. And `ManifoldSurfaceMesh` derives from `SurfaceMesh`. But it seemed to me to be the least-of-all evils to just drop these properties the moment you use the more general mesh type, rather than having them sometimes hold and other times not.

@nzfeng I can't think of adjustments that would give the desired behavior, but I'm open to ideas! Let me know if this all makes sense....

**Comment by nmwsharp** [comment]
> ManifoldSurfaceMesh without borders. I would expect that assert(h.edge().halfedge() == h) holds for all halfedges, but it does not.

Maybe I misunderstand, but I don't think this is a reasonable behavior. Each edge can only have one of its incident halfedges as the target of its `edge.halfedge()` reference, so this property can't hold for both incident halfedges.

**Comment by afabri** [comment]
> > ManifoldSurfaceMesh without borders. I would expect that assert(h.edge().halfedge() == h) holds for all halfedges, but it does not.
> 
> Maybe I misunderstand, but I don't think this is a reasonable behavior. Each edge can only have one of its incident halfedges as the target of its `edge.halfedge()` reference, so this property can't hold for both incident halfedges.

The boost graph library has no halfedges but has edges with source and target, and an out edge iterator for vertices. That means that I write [another edge type](https://github.com/CGAL/cgal/pull/8480/files#diff-83834885a097ce37be7fa4979ccc7a3454cce09c5de383086b7aab19fb42aafcR68) which stores a halfedge and two edges are considered equal  when the halfeges are equal or one is the twin of the other.  But that does not require any changes in geometrycentral and is an implementation detail of the specialization of the `boost::graph_traits<>`.  

Thanks to all of you for the explanations and clarifications.  Let me c;lose the issue.

**Comment by nzfeng** [comment]
Thanks for the explanations, Nick! Makes sense what you said about the general `SurfaceMesh` object.
