### ISSUE TITLE
Vector::normalize() violates principle of least surprise

### ISSUE THREAD

**Issue by keenancrane** [nmwsharp/geometry-central#41]
Because of the way it's named, `Vector::normalize()` yields unexpected behavior: the verb-forming suffix "-ize" implies a transitive verb that acts on the vector itself, as in, _"We then normalize the vector."_  The expected behavior of `v.normalize()` is hence that `v` itself gets modified, whereas the current behavior is to return a normalized version of `v`. [The behavior is spelled out in the documentation, but causes confusion nonetheless.]

**Proposal:** Add a method `Vector::unit()` that returns the unit version of the given vector.  Deprecate `Vector::normalize()` (by removing it from the documentation) to preserve compatibility with existing code.

Though in a perfect world `normalize()` would mutate the vector itself, making that change now would likely wreak havok.

**Comment by nmwsharp** [comment]
I actually did a small survey trying to see what the most common conventions are for functions like this in various libraries, anddddddd the answer is there's no consistent convention whatsoever :upside_down_face:. Various popular libraries are all over the place. 

I settled on the following policies to keep things somewhat same:

- There are no functions which modify a vector in-place. They are _always_ return a new vector. This way you don't have to constantly check which ones mutate and which ones are pure.

- I borrowed GLSL/GLM naming in most places, since these these are widely-known and have trickled in to other projects as a result. For instance, [GLSL/GLM defines a `normalize()` function](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/normalize.xhtml) which returns a new vector. 

However, even this naming is by no means universal of course. For instance, [Eigen](https://eigen.tuxfamily.org/dox/classEigen_1_1MatrixBase.html#ad16303c47ba36f7a41ea264cb26bceb6) defined a `normalize()` function which mutates in place, and a `normalized()` function which is pure! I like the Eigen convention, except that the names are so similar and easy to mix up.

I have no problem with adding an additional `Vector::unit()` function which is an alias for `normalize()`. I'll argue for keeping `normalize()`, however, since it is what some people will expect.

**Comment by nmwsharp** [comment]
Also, this is exactly what the `[[nodiscard]]` attribute is meant for, if/when we ever bump the language requirement to C++17! It'll make the compile emit a warning if you don't use the result of a `normalize()`, preventing most of these errors. One day....

**Comment by keenancrane** [comment]
> I actually did a small survey trying to see what the most common conventions are…

I vote that we choose conventions that are consistent with the English language—which (I believe) is spoken more broadly than either GLM or Eigen. ;-)

But ok, adding `Vector::unit()` sounds like a reasonable option. `[[nodiscard]]` sounds nice too.

**Comment by nmwsharp** [comment]
953ad377ce2221de8fa01263bbb63361b0bcab53 adds support for all combinations of `Vector2` / `Vector3` as:

```cpp
Vector3 v = /* something */;
Vector3 u;
u = unit(v);
u = normalize(v);
u = v.unit();
u = v.normalize();
```

This change does not break existing code.

Closing for now! Feel free to reopen if you want to chat more about naming & conventions for this.
